FEAT: criação tela cadastro paciete
givisiez-JDM/PADA-frontend pull request #30
Opened 2024-01-21 22:05 UTC by AndressaMac

2024-01-30 22:22 UTC, rafonha requested changes, later dismissed
- verificar padrão de tamanhos
- verificar padrão de cores
- verificar identação e espaços
- verificar tags usadas diretamente sem ser do styled components
- mudar importação do react

2024-01-30 22:22 UTC, rafonha commented on src/components/button/Button.tsx
> +<<<<<<< HEAD
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/button/Button.tsx
> +=======
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/button/Button.tsx
> +>>>>>>> 5bfbb64a563db6b85e53492513b41285ca609d53
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuContainer/MenuContainer.styles.ts
> +<<<<<<< HEAD
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuContainer/MenuContainer.styles.ts
> +=======
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuContainer/MenuContainer.styles.ts
> +>>>>>>> 5bfbb64a563db6b85e53492513b41285ca609d53
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.styles.ts
> +<<<<<<< HEAD
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.styles.ts
> +=======
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.styles.ts
> +  z-index: 1;
Verificar a necessidade de usar o z-index

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.styles.ts
> +export const HeaderGreeting = styled.p`
Melhorar legibilidade do nome do componente

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.styles.ts
> +>>>>>>> 5bfbb64a563db6b85e53492513b41285ca609d53
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.tsx
> +<<<<<<< HEAD
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.styles.ts
>  // import styled from "styled-components";
Deletar essas linhas de comentário, por que está comentado?

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.tsx
>  // import {
deletar essas linhas de comentário, por que elas estão comentadas?

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.tsx
> +=======
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.tsx
> +      <HeaderImage>LOGO</HeaderImage>
isso é um texto?

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.tsx
> +        <HeaderImage>FOTO</HeaderImage>
onde está sendo importada essa foto?

2024-01-30 22:22 UTC, rafonha commented on src/components/menuMedicoHeader/MenuMedicoHeader.tsx
> +>>>>>>> 5bfbb64a563db6b85e53492513b41285ca609d53
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +display: flex;
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +  font-size: 2.188rem;
falta identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +  border: none ;
deletar espaço

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +width: 22px;
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +  border-radius:50%;
falta espaço entre : e 50

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> + position:relative;
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +    font-size: larger;
de onde está vindo o tamanho larger? onde foi definido esse tamanho?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +display: flex;
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +.ContentInput{
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +.date{
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +label{
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +export const RegisterAlergis = styled.div`
Corrigir nome

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +display: flex;
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +h2{
identação e faltando espaço entre 2 e {

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +.inputCheckbox{
identação e faltando espaço entre o x e {

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +p{
identação e falta um espaço entre p e {

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +.duration{
indentação e falta espaço entre n e {

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +.labelTreatment{
Adicionar essa linha, identação e falta espaço entre t e {

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +.medication{
adicionar uma linha, identação e falta espaço entre n e {

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +  height: 2rem!important;
NÃO PODE USAR !important DE JEITO NENHUM!!

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +  width: 16.313rem!important;
NÃO PODE USAR !important DE JEITO NENHUM!!

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +const newpatient = z.object({
newPatient nomenclatura

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +  alergia: z.string(),
traduzir para inglês

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +const CadastroPaciente = () => {
Criar o componente desestruturando o React

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> + // const url = 'https://app-vacina-production.up.railway.app/doctors/patient-register'
Não ter comentário no código, por que está comentado?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +   // const values = {...getValues()}
por que está comentado?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> + // console.log("VALUES",getValues())
por que está comentado?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +        alt="Remy Sharp"
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +       </AvatarConatiner>
Erro na escrita

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +<ContentRegister>
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Deletar essa linha

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +  <div className="ContentInput">
por que é uma div usando uma classe? por que não um container do styled component?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +    <label>Nome</label>
por que é uma label usando uma classe? por que não um label do styled component?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +  <RegisterAlergis>
Corrigir nome

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +    <div className="inputCheckbox">
por que é uma div usando uma classe? por que não um container do styled component?

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +<ContentTreatment>
identação

2024-01-30 22:22 UTC, rafonha commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +  { Metodos.map((field) => (
remover o espaço e adicionar identação

2024-04-01 17:24 UTC, artphil reviewed
O aplicativo não passa da tela de login. Favor conferir qual erro está acontecendo.
Fazer Pull de develop para puxar as ultimas atualizações.

2024-04-01 17:24 UTC, artphil commented on src/components/menuHeader/MenuHeader.styles.ts
> +  height: 115px;
Utilizar rem no lugar de px

2024-04-01 17:24 UTC, artphil commented on src/global/UserContext.tsx
> +
remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.tsx
> +
Remover linha em branco

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-01 17:24 UTC, artphil commented on src/pages/cadastroPaciente/CadastroPacientePage.styles.ts
> +`
Adicionar ponto e vírgula

2024-04-02 20:16 UTC, yasminconc approved these changes

2024-04-04 12:19 UTC, artphil approved these changes

2024-04-05 20:01 UTC, artphil reviewed
Corrigido

2024-04-05 20:02 UTC, artphil approved these changes
Conflitos corrigidos

2024-04-05 20:06 UTC, merged