Feat: Criação da tela fase de tratamento
givisiez-JDM/PADA-frontend pull request #32
Opened 2024-01-22 16:04 UTC by yasminconc

# Fase de tratamento

<h4>📍Desenvolvido por Yasmin Conc<h4/>

✅ Tarefas finalizadas

* Header contendo foto, nome do paciente e opção de sair
* Navegação lateral contendo a opção de Perfil, Fases e Vacinas
* Duração da fase
* Periodicidade
* Dosagem do medicamento
* Progresso da fase
* botão alterar fase
* botão finalizar fase
* botão add fase 
* Modal para a adição de uma nova fase

<br/>

![image](https://github.com/givisiez-JDM/PADA-frontend/assets/98767110/7a4199ce-b271-43e6-91d5-47e6e61e5ea1)

![image](https://github.com/givisiez-JDM/PADA-frontend/assets/98767110/e41a08e1-495e-471b-9ba2-0be9088be359)

![image](https://github.com/givisiez-JDM/PADA-frontend/assets/98767110/e54fe6c1-1674-46f3-8dfa-3e5744d64895)

2024-02-20 00:51 UTC, artphil requested changes

2024-02-20 00:51 UTC, artphil commented on src/components/Header/styles.ts
nome fora do padrão, pasta em minúsculo e Element.styles.ts  => header/Header.styles.ts

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/index.tsx
nome fora do padrão, pasta em minúsculo e Element.tsx

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/index.tsx
> +                  <p>1.3ml</p>
isso deveria ser fixo? sugestão: utilizar array.map()

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/index.tsx
> +                <label htmlFor="">A cada 7 dias</label>
isso deveria ser fixo? sugestão: utilizar array.map()

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/styles.ts
nome fora do padrão, pasta em minúsculo e Element.styles.ts

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/styles.ts
> +
Remover linha em branco

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/styles.ts
> +
Remover linha em branco

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/styles.ts
> +
Remover linha em branco

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/styles.ts
> +
Remover linha em branco

2024-02-20 00:51 UTC, artphil commented on src/components/ModalTreatmentPhase/styles.ts
> +
Remover linha em branco

2024-02-20 00:51 UTC, artphil commented on src/global/UserContext.tsx
> +  // useEffect(() => {
remover comentários

2024-02-20 00:51 UTC, artphil commented on src/pages/FaseDeTratamento/index.tsx
nome fora do padrão, pasta em minúsculo e Element.tsx

2024-02-20 00:51 UTC, artphil commented on src/pages/FaseDeTratamento/styles.ts
nome fora do padrão, pasta em minúsculo e Element.styles.ts

2024-02-20 00:51 UTC, artphil commented on src/pages/FaseDeTratamento/styles.ts
> +
Remover linha em branco

2024-02-20 00:51 UTC, artphil commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.styles.ts
arquivo comentado. Excluir ou adicionar TODO

2024-02-20 00:51 UTC, artphil commented on src/pages/vacinasPaciente/vaccine/Vaccine.tsx
> +            {/* <VaccineDate className={getVaccineStatus()}>{applicationDate || scheduledDate}</VaccineDate> */}
porque está comentado?

2024-02-20 00:51 UTC, artphil commented on src/router/Router.tsx
> +import GlobalStorage from '../global/UserContext'
aspas fora do padrão

2024-02-20 00:51 UTC, artphil commented on src/types/LoginTypes.ts
> +import { formLogiValidate } from '../Hooks/useForm'
fora do padrão: nome da pasta minúsculo

2024-02-20 00:51 UTC, artphil commented on src/types/SignupTypes.ts
> +import { formValidateSignup } from "../Hooks/useForm"
fora do padrão: nome da pasta minúsculo

2024-02-22 21:05 UTC, yasminconc reviewed
Finalizado as alterações

2024-02-23 18:47 UTC, artphil commented
Condição de aceite não alcançada
* Selecionar apenas 01 check box de cada seção

2024-02-27 15:39 UTC, artphil approved these changes
Aprovado

2024-02-27 15:42 UTC, merged