feat: [PADA 195] tela fases de tratamento
givisiez-JDM/PADA-frontend pull request #40
Opened 2024-03-15 18:44 UTC by artphil

Tela fases de tratamento.

Partes desenvolvidas nessa tarefa:
* Apresentação das fases de Tratamento em forma de menu expansível.
* Card  com indicação do progresso do tratamento.
* Rotas para criação e edição de fases.
* Função Finalizar a fase.

![Sem título](https://github.com/givisiez-JDM/PADA-frontend/assets/10052259/c76218d7-bc64-4f6c-881c-d967e05dc04d)
Quando o paciente não tem fase registrada no sistema, existe apenas a função de Adicionar fase.

![Sem título-1](https://github.com/givisiez-JDM/PADA-frontend/assets/10052259/f6a8ebbb-3538-41c4-b229-248a30cb7b27)
Quando existem fases elas são apresentadas em forma de lista e a opção de Finalizar fase fica visível.

![Sem título](https://github.com/givisiez-JDM/PADA-frontend/assets/10052259/2646fd79-3c01-43fe-88dd-e0ee21478c53)
Ao clicar no título da fase, mostra-se as informações dela e a opção de alterar a fase.

OBS:
* O Card de progresso difere do modelo no Figma. O novo modelo foi acertado entre o time de FE e o time de UX
* A tela de Alteração de Fase e Adicionar Fase não estão concluídas. Aqui têm as rotas para elas apenas.
* Existe lentidão para apresentar os dados devido a quantidade de requisições necessárias para apresentá-los.

2024-03-15 20:55 UTC, marianapcorrea commented on src/components/button/Button.tsx
> +import { ButtonHTMLAttributes, FC } from 'react'
Ponto e vírgula

2024-03-15 20:56 UTC, marianapcorrea commented on src/components/button/Button.tsx
> +  const className = size ?? 'normal'
Ponto e vírgula

2024-03-15 20:57 UTC, marianapcorrea commented on src/components/patientHeader/PatientHeader.tsx
> +      <Close to={'/menu-medico'}>
Tag sem fechamento?

2024-03-15 21:40 UTC, artphil reviewed
Corrigido

2024-03-15 21:40 UTC, artphil commented on src/components/button/Button.tsx
> +import { ButtonHTMLAttributes, FC } from 'react'
ok

2024-03-15 21:40 UTC, artphil commented on src/components/button/Button.tsx
> +  const className = size ?? 'normal'
ok

2024-03-15 21:40 UTC, artphil commented on src/components/patientHeader/PatientHeader.tsx
> +      <Close to={'/menu-medico'}>
Fechamento na linha 28

2024-03-19 18:11 UTC, marianapcorrea requested changes
- Ponto e vírgula
- Padronização de aspas
- Correções gramaticais de variáveis em inglês
- Sugestão de alteração de nomes de variáveis.

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>        window.localStorage.setItem('id', req.data.user.id)
Ponto e vírgula ?

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  }
Ponto e vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  const hasPhases = () => phaseList.length > 0
Ponto e vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +    if (!phaseSelected) return
Ponto e vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/components/button/Button.tsx
>  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/components/phaseProgress/PhaseProgress.tsx
> +}
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/components/phaseProgress/PhaseProgress.tsx
> +}
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>    const [userId, setUserId] = useState<any | null>(null)
Falta Ponto e Vírgula no fim das linhas 40, 42, 44, 49 e 58

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  const [tokenState, setTokenState] = useState('');
Padronizar para aspas duplas ou simples em todas as declarações de estado (conferir linhas 61 a 69)

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +      setToken(req.data.token)
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>    }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>        const { url, headers } = userRequest.GET_DOCTOR_BY_ID(userId, token)
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>        const req = await axios.get(url, { headers })
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>    }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
> +    setToken('');
Linha 267, linha 270: Padronizar aspas duplas ou simples

2024-03-19 18:11 UTC, marianapcorrea commented on src/global/UserContext.tsx
>    }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +    vaccineList
Virgula após elemento

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +    const total = vaccineList.length
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +      if (vaccine.status !== 'agendado')
Ou colocar o return na mesma linha do if, ou colocá-lo dentro de { }

Adicionar Ponto e Vírgula após cada return

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +            <img src={phaseSelected?.phaseNumber === phase.phaseNumber ? IconArrowUp : IconArrowDown} alt="Mostrar conteúdo" />
Linha muito longa

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  }
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/perfilPaciente/PerfilPacientePage.tsx
> +import { Alergis, ArticleContact, ArticleEmail, ArticleName, Born, Button, Main, MethodTreatment, Middle, Section, Tel, Title, TitleTreatment, Treatment, TreatmentContainer, TreatmentDuration } from
Linha muito grande.
* Se 'Alergis' for referente à palavra "alergias" em inglês, o correto é 'Allergies'.
* Talvez 'born' fique melhor como 'dateOfBirth' (data de nascimento).
* Mudar 'TitleTreatment' para "TreatmentTitle. Fica mais claro e segue o padrão dos outros elementos derivados de treatment.

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +
Remover linha em branco duplicada;

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +              >Finalizar Fase</Button>}
Quebrar linha antes do '>', antes do fechamento de tag </Button> e antes do "}"

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +            {hasPhases() &&
Quebrar linha após o "{"

2024-03-19 18:11 UTC, marianapcorrea commented on src/pages/treatmentPhases/phase/Phase.tsx
> +}
Ponto e Vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/types/TreatmentTypes.ts
> +export type AllergieType = 'comida' | 'vespa' | 'ácaro' | 'gato' | 'bola' | 'inseto' | 'abelha' | 'formiga' | 'cachorro' | 'barata' | 'fungos' | 'candidíase'
'Alergia' em inglês é 'Allergy'
Linha muito grande

Ponto e vírgula (linhas 1 a 3)

2024-03-19 18:11 UTC, marianapcorrea commented on src/types/TreatmentTypes.ts
>  }
Ponto e vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/types/TreatmentTypes.ts
>  }
Ponto e vírgula

2024-03-19 18:11 UTC, marianapcorrea commented on src/types/TreatmentTypes.ts
>  export type VaccineType = {
Ponto e vírgula fechando objeto.

2024-03-19 20:32 UTC, artphil reviewed
modificações realizadas

2024-03-19 20:32 UTC, artphil commented on src/components/button/Button.tsx
>  }
ok

2024-03-19 20:32 UTC, artphil commented on src/components/phaseProgress/PhaseProgress.tsx
> +}
ok

2024-03-19 20:32 UTC, artphil commented on src/components/phaseProgress/PhaseProgress.tsx
> +}
ok

2024-03-19 20:32 UTC, artphil commented on src/global/UserContext.tsx
>    const [userId, setUserId] = useState<any | null>(null)
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/perfilPaciente/PerfilPacientePage.tsx
> +import { Alergis, ArticleContact, ArticleEmail, ArticleName, Born, Button, Main, MethodTreatment, Middle, Section, Tel, Title, TitleTreatment, Treatment, TreatmentContainer, TreatmentDuration } from
Essa tela foge ao escopo dessa tarefa, precisei alterar a linha 58 para corrigir um bug, mas o resto ficará para uma próxima. As linhas em destaque são culpa do prettier.

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +    vaccineList
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  }
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  const hasPhases = () => phaseList.length > 0
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +    if (!phaseSelected) return
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  }
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +    const total = vaccineList.length
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +      if (vaccine.status !== 'agendado')
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +            <img src={phaseSelected?.phaseNumber === phase.phaseNumber ? IconArrowUp : IconArrowDown} alt="Mostrar conteúdo" />
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +  }
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/TreatmentPhases.tsx
> +              >Finalizar Fase</Button>}
ok

2024-03-19 20:32 UTC, artphil commented on src/pages/treatmentPhases/phase/Phase.tsx
> +}
não aceitou por ser interface

2024-03-19 20:32 UTC, artphil commented on src/types/TreatmentTypes.ts
> +export type AllergieType = 'comida' | 'vespa' | 'ácaro' | 'gato' | 'bola' | 'inseto' | 'abelha' | 'formiga' | 'cachorro' | 'barata' | 'fungos' | 'candidíase'
ok

2024-03-19 20:32 UTC, artphil commented on src/types/TreatmentTypes.ts
>  }
ok

2024-03-19 20:32 UTC, artphil commented on src/types/TreatmentTypes.ts
>  }
ok

2024-03-19 20:32 UTC, artphil commented on src/types/TreatmentTypes.ts
>  export type VaccineType = {
ok

2024-03-20 15:46 UTC, artphil reviewed
concluido

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
>    }
ok

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
> +  }
ok

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
> +  }
ok

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
> +  }
ok

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
> +  }
ok

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
> +  }
ok

2024-03-20 15:46 UTC, artphil commented on src/global/UserContext.tsx
>    }
ok

2024-03-21 17:29 UTC, artphil reviewed
corrigido

2024-03-21 17:29 UTC, artphil commented on src/components/button/Button.tsx
>  }
interface não aceita

2024-03-21 17:29 UTC, artphil commented on src/components/phaseProgress/PhaseProgress.tsx
> +}
interface não aceita

2024-03-24 22:36 UTC, marianapcorrea approved these changes

2024-03-25 16:52 UTC, merged