feat: [Pada 249] componentizar checkbox
givisiez-JDM/PADA-frontend pull request #41
Opened 2024-03-26 18:28 UTC by artphil

Criado um componente checkbox, com base na tela de edição de fase, para ser usado em outras telas. 

![checkbox](https://github.com/givisiez-JDM/PADA-frontend/assets/10052259/dc4dd8f3-8a73-4eca-9b63-2d0ce05038df)

2024-04-02 13:17 UTC, marianapcorrea requested changes
Solicitações de mudança:
- Adição de ponto e vírgula;
- Verificação de nome repetido de elementos;
- Quebra de linha para diminuir comprimento da linha.

Não foi possível verificar a funcionalidade no preview do Deploy, pois precisei criar um cadastro para acessar a aplicação e não possuo, nesses cadastros, dados de pacientes, nem é possível criá-los, já que essa funcionalidade ainda não foi adicionada.

2024-04-02 13:17 UTC, marianapcorrea commented on src/components/checkbox/Checkbox.tsx
> +  const inputId = id ?? String(value)
Ponto e Vírgula

2024-04-02 13:17 UTC, marianapcorrea commented on src/components/checkbox/Checkbox.tsx
> +  const inputType = type ?? "checkbox"
Ponto e Vírgula

2024-04-02 13:17 UTC, marianapcorrea commented on src/components/checkbox/Checkbox.tsx
> +}
Ponto e Vírgula

2024-04-02 13:17 UTC, marianapcorrea commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
>            <ConteinerCheckBox>
Achei confuso esse elemento de FasesDeTratamento ser chamado "ConteinerCheckBox", e haver no components/checkbox um outro elemento de nome "ConteinerCheckbox". 

Será que não é melhor trocar o nome de um deles para ficar mais legível?
Sei que são escopos diferentes e por isso não gera conflito, mas fica confuso para quem lê o código.

2024-04-02 13:17 UTC, marianapcorrea commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
> +              <Checkbox name="frequency" type="radio" label={"A cada " + frequency} value={frequency} key={frequency} />
Linha muito comprida. Melhor quebrar os atributos em linhas individuais.

2024-04-02 13:17 UTC, marianapcorrea commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
>            <ConteinerCheckBox>
Mesmos comentários acima

2024-04-02 13:17 UTC, marianapcorrea commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
> +              <Checkbox name="dosage" type="radio" label={dosage + "g"} value={dosage} key={dosage} />
Mesmos comentários acima

2024-04-02 19:13 UTC, artphil reviewed
demandas concluidas

2024-04-02 19:13 UTC, artphil commented on src/components/checkbox/Checkbox.tsx
> +  const inputId = id ?? String(value)
ok

2024-04-02 19:13 UTC, artphil commented on src/components/checkbox/Checkbox.tsx
> +  const inputType = type ?? "checkbox"
ok

2024-04-02 19:13 UTC, artphil commented on src/components/checkbox/Checkbox.tsx
> +}
ok

2024-04-02 19:13 UTC, artphil commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
>            <ConteinerCheckBox>
Isso foi corrigido na PADA-180 que é específica desta tela.

2024-04-02 19:13 UTC, artphil commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
> +              <Checkbox name="frequency" type="radio" label={"A cada " + frequency} value={frequency} key={frequency} />
feito

2024-04-02 19:13 UTC, artphil commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
>            <ConteinerCheckBox>
ok

2024-04-02 19:13 UTC, artphil commented on src/pages/fasesDeTratamento/FasesDeTratamentoPage.tsx
> +              <Checkbox name="dosage" type="radio" label={dosage + "g"} value={dosage} key={dosage} />
ok

2024-04-03 17:26 UTC, marianapcorrea approved these changes

2024-04-05 20:08 UTC, merged