Feat: [PADA-185] Edicao dados medico
givisiez-JDM/PADA-frontend pull request #55
Opened 2024-07-04 23:25 UTC by Gonteejo

Página de edição dos dados do medico.
Para acessá-la abra o modal ao lado do nome do médico, vá à tela "Meu perfil" e clique no botão alterar no cartão de progresso.

![image](https://github.com/givisiez-JDM/PADA-frontend/assets/96489350/7ac3de19-a042-427a-a6f3-6a3f330e84a2)

Abaixo segue tela do figma:

![image](https://github.com/givisiez-JDM/PADA-frontend/assets/96489350/cdf12fc5-c4ff-418f-9f14-9d2f5b0da370)

2024-07-06 21:11 UTC, artphil requested changes
Ficou muito boa a página e bem fiel ao figma.
Apontei alguns pontos que fogem ao padrão (que é usar o tema) e outros, que apesar de não termos dicutido não é o que vem sendo utilizado no resto do projeto ( uso das palavras BOLD, NORMAL, etc...). Fica a seu critério mudar ou não esse segundo.

segue as relações de equivalencia das palavras e valores caso tenha interesse;
https://www.w3.org/TR/css-fonts-3/#propdef-font-weight

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    font-weight: bold;
Porque o uso de BOLD?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    font-weight: bold;
Porque o uso de BOLD?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    font-weight: bold;
Porque o uso de BOLD?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    font-weight: bold;
bold equivale a 700

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    line-height: normal;
Porque o uso de NORMAL?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    font-weight: bold;
Porque o uso de BOLD?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/PerfilMedicoPage.styles.ts
> +    line-height: normal;
Porque o uso de NORMAL?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  color: white;
Usar cores do tema

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  font-size: larger;
Porque o uso de tamanho relativo na font?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  font-weight: bold;
Porque o uso de BOLD?

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  border: 1px solid #ccc;
Usar cores do tema

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  border: 1px solid #ccc;
No Figma é utilizado a cor #334C76 qaue é a Variante3

2024-07-06 21:11 UTC, artphil commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  font-family: 'poppins', sans-serif;
Retirar essa linha para utilizar a fonte padrão "Noto Sans KR"

2024-07-08 22:27 UTC, Gonteejo commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  font-size: larger;
Esse font-size está em todo cabeçalho do médico, já estava dessa forma.
Interessante seria componentizar esse header e fazer a correção.

Esse é um arquivo antigo que não tem relação com minha pada para ter uma noção:
![Imagem do WhatsApp de 2024-07-08 à(s) 19 15 20_46f2960f](https://github.com/givisiez-JDM/PADA-frontend/assets/96489350/d9df1e35-87cf-4782-8082-54098b9011c2)

2024-07-08 22:30 UTC, Gonteejo commented on src/pages/perfilMedico/editarPerfil/EditarPerfil.styles.ts
> +  border: 1px solid #ccc;
Na realidade o codigo estava duplicado, removi a linha 79 mantendo somente a 81.

![image](https://github.com/givisiez-JDM/PADA-frontend/assets/96489350/a7659aab-0702-4c8c-a520-6573024c8dbe)

2024-07-09 10:51 UTC, artphil approved these changes
Bom trabalho

2024-07-09 16:19 UTC, merged